### ISSUE TITLE
JuliaCon blockers

### ISSUE THREAD

**Issue by ashton314** [utahplt/TrackedFloats.jl#46]
Copied from list of issues here: https://github.com/JuliaCon/proceedings-review/issues/148#issuecomment-2222008483

 * [x]  rename FloatTracker.jl to TrackedFloats.jl
 * [x]  add contributor guidelines
 * [x]  add a license to CSTG
 * [ ]  add structure to the TF.jl documentation
 * [ ]  make sure TF.jl has appropriate API documentation.
 * [x]  export only functions that start with `ft_`

**Comment by ashton314** [comment]
Renaming of exported functions complete.

Docs will remain the same; this is a small tool and the README should suffice for anyone sufficiently interested to try out our package.

**Comment by bennn** [comment]
✅
